{'id': '3c7300a2c603e23e4cd87f07cdc5c34f',
 'timestamp': datetime.datetime(2025, 11, 20, 9, 28, 20, 473000, tzinfo=datetime.timezone.utc),
 'name': 'call_llm',
 'input': {'model': 'azure/gpt-4o-mini',
  'config': {'system_instruction': '\n        **Role:** Host agent for the agent-to-agent protocol; delegates queries to specialized remote agents with maximum efficiency.\n\n**Core Directives:**\n\n* **Task Delegation:** Use the `send_message` function to assign precise, actionable tasks to remote agents.\n* **Full Context Provision:** If an agent repeatedly asks for user confirmation, it likely lacks conversation history. Include all relevant context in the task to prevent this.\n* **Autonomous Multi-Agent Engagement:** Engage any required agents directly—never seek user permission or preference. If multiple agents are needed, orchestrate them seamlessly.\n* **Intelligent Inter-Agent Collaboration:** Instruct agents to determine if they need data from another agent. **If Agent A says "I need X to proceed" and Agent B can provide X, immediately query Agent B, then resubmit the updated task to Agent A.**\n* **Transparent Output:** Deliver the full, unedited response from the final agent(s) to the user.\n* **Confirmation Handling:** Only relay confirmation requests to the user if not already provided. Never confirm on behalf of the user.\n* **Minimal Context Sharing:** Share only task-relevant context with each agent. Omit irrelevant details.\n* **No Redundancy:** Never ask agents to confirm actions or information.\n* **Tool-Only Responses:** Rely exclusively on tools and agents. If data is missing, request clarification from the user—never assume.\n* **Recency Priority:** Base decisions on the most recent user message.\n* **Active Agent Routing:** Route follow-up queries to the currently active agent using task updates.\n\n**Efficiency Rule:** \n> **Dependency Resolution Loop:**  \n> If Agent A blocks on missing info → Identify Agent B that can supply it → Query B → Feed result back to A → Repeat until A completes or escalates.\n        **Agent Roster:**\n\n        * Available Agents: `{"name": "Capital Agent", "description": "Answers capital-city questions for any country"}\n{"name": "General Q&A Agent", "description": "Answers everyday questions on any topic \\u2014 weather, facts, how-to, recommendations, and more."}`\n        * Currently Active Seller Agent: `Capital Agent`\n                \n\nYou are an agent. Your internal name is "Routing_agent". The description about you is "This Routing agent orchestrates the decomposition of the user asking for department or manager information.".',
   'tools': [{'function_declarations': [{'description': 'Sends a task to remote seller agent.\n\nThis will send a message to the remote agent named agent_name.\n\nArgs:\n    agent_name: The name of the agent to send the task to.\n    task: The comprehensive conversation context summary\n        and goal to be achieved regarding user inquiry and purchase request.\n    tool_context: The tool context this method runs in.\n\nYields:\n    A dictionary of JSON data.\n',
       'name': 'send_message',
       'parameters': {'properties': {'agent_name': {'type': 'STRING'},
         'task': {'type': 'STRING'}},
        'required': ['agent_name', 'task'],
        'type': 'OBJECT'},
       'response': {}}]}],
   'labels': {'adk_agent_name': 'Routing_agent'}},
  'contents': [{'parts': [{'text': 'what is the capital of Pakistan and write 10 lines about it.'}],
    'role': 'user'},
   {'parts': [{'function_call': {'id': 'call_2kkSR1RTSkhmWq7mei1gcBgB',
       'args': {'agent_name': 'Capital Agent',
        'task': 'User requested the capital of Pakistan and a 10-line description about it.'},
       'name': 'send_message'}}],
    'role': 'model'},
   {'parts': [{'function_response': {'id': 'call_2kkSR1RTSkhmWq7mei1gcBgB',
       'name': 'send_message',
       'response': {'result': {'artifacts': [{'artifactId': '3d9b7caa-07e0-45c0-a38a-cc8e3948cdac',
           'parts': [{'kind': 'text', 'text': 'Islamabad'}]}],
         'contextId': 'b6b6d2ce-ca8a-43e5-adbe-999eba9ebd1c',
         'history': [{'contextId': 'b6b6d2ce-ca8a-43e5-adbe-999eba9ebd1c',
           'kind': 'message',
           'messageId': '2aff8a91-f6c0-4fe4-8b98-45aff71b2cf3',
           'parts': [{'kind': 'text', 'text': 'Islamabad'}],
           'role': 'agent'}],
         'id': '998fde21-2f6a-4116-8669-b48ad0d278d9',
         'kind': 'task',
         'status': {'state': 'completed'}}}}}],
    'role': 'user'}]},
 'output': {'content': {'parts': [{'function_call': {'id': 'call_pQA9a3Ea1lmhaEp6r4EdsWto',
      'args': {'agent_name': 'General Q&A Agent',
       'task': 'User asked for a 10-line description of Islamabad, the capital of Pakistan.'},
      'name': 'send_message'}}],
   'role': 'model'},
  'partial': False,
  'usage_metadata': {'candidates_token_count': 38,
   'prompt_token_count': 921,
   'total_token_count': 959}},
 'metadata': {'attributes': {'gen_ai.system': 'gcp.vertex.agent',
   'gen_ai.request.model': 'azure/gpt-4o-mini',
   'gcp.vertex.agent.invocation_id': 'e-1773c2c0-9fb0-4741-bf2f-4936346cf4da',
   'gcp.vertex.agent.session_id': 'default_session',
   'gcp.vertex.agent.event_id': '5de324d5-9cd4-470e-b86c-83dbc92187b3',
   'gen_ai.usage.input_tokens': '921',
   'gen_ai.usage.output_tokens': '38'},
  'resourceAttributes': {'telemetry.sdk.language': 'python',
   'telemetry.sdk.name': 'opentelemetry',
   'telemetry.sdk.version': '1.38.0',
   'service.name': 'unknown_service'},
  'scope': {'name': 'gcp.vertex.agent',
   'version': '1.17.0',
   'attributes': {}}},
 'tags': [],
 'public': False,
 'environment': 'default',
 'htmlPath': '/project/cmhwzwyvs01fjad07xfmlp94h/traces/3c7300a2c603e23e4cd87f07cdc5c34f',
 'latency': 8.731,
 'totalCost': 0.0,
 'observations': [{'id': '6eda86706e8e2b96',
   'traceId': '3c7300a2c603e23e4cd87f07cdc5c34f',
   'type': 'AGENT',
   'name': 'rohit',
   'startTime': datetime.datetime(2025, 11, 20, 9, 28, 23, 210000, tzinfo=datetime.timezone.utc),
   'endTime': datetime.datetime(2025, 11, 20, 9, 28, 29, 196000, tzinfo=datetime.timezone.utc),
   'completionStartTime': None,
   'model': None,
   'modelParameters': {},
   'input': {'args': [],
    'kwargs': {'message_request': {'id': 'ed341398-ed9e-4d38-bf1f-2676650741c3',
      'jsonrpc': '2.0',
      'method': 'message/send',
      'params': {'configuration': None,
       'message': {'contextId': '2b2860c5-50fe-4b8e-9ba6-cc77817fd6d7',
        'extensions': None,
        'kind': 'message',
        'messageId': 'ed341398-ed9e-4d38-bf1f-2676650741c3',
        'metadata': None,
        'parts': [{'kind': 'text',
          'metadata': None,
          'text': 'User asked for a 10-line description of Islamabad, the capital of Pakistan.'}],
        'referenceTaskIds': None,
        'role': 'user',
        'taskId': None},
       'metadata': None}}}},
   'version': None,
   'metadata': {'resourceAttributes': {'telemetry.sdk.language': 'python',
     'telemetry.sdk.name': 'opentelemetry',
     'telemetry.sdk.version': '1.38.0',
     'service.name': 'unknown_service'},
    'scope': {'name': 'langfuse-sdk',
     'version': '3.10.0',
     'attributes': {'public_key': 'pk-lf-f69fce2c-2a85-44c6-8777-646b07f7ccaf'}}},
   'output': {'id': 'ed341398-ed9e-4d38-bf1f-2676650741c3',
    'jsonrpc': '2.0',
    'result': {'artifacts': [{'artifactId': '22299dc1-62cd-4858-aa76-32eb0b695121',
       'description': None,
       'extensions': None,
       'metadata': None,
       'name': None,
       'parts': [{'kind': 'text',
         'metadata': None,
         'text': "Islamabad is the capital city of Pakistan, officially established in 1967 to replace Karachi as the nation's capital. Located in the northern part of the country near the Margalla Hills, the city was purposefully designed and built as a modern planned capital. The city is known for its well-organized layout, wide tree-lined avenues, and systematic sectoral divisions that create an orderly urban environment. Islamabad houses important government buildings, including the Presidential Palace, Parliament House, and Supreme Court of Pakistan. The city is characterized by its clean, green environment with numerous parks, gardens, and the scenic Margalla Hills National Park nearby. Home to several prestigious educational institutions like Quaid-i-Azam University and the International Islamic University, it serves as an important academic center. The population is diverse, consisting of government officials, diplomats, professionals, and students from across Pakistan and abroad. Islamabad's economy is primarily based on government services, though it also has growing technology and business sectors. The city experiences a humid subtropical climate with hot summers and mild winters. As Pakistan's political and administrative center, Islamabad plays a crucial role in the country's governance and international diplomatic relations."}]}],
     'contextId': '2b2860c5-50fe-4b8e-9ba6-cc77817fd6d7',
     'history': [{'contextId': '2b2860c5-50fe-4b8e-9ba6-cc77817fd6d7',
       'extensions': None,
       'kind': 'message',
       'messageId': 'ed341398-ed9e-4d38-bf1f-2676650741c3',
       'metadata': None,
       'parts': [{'kind': 'text',
         'metadata': None,
         'text': "Islamabad is the capital city of Pakistan, officially established in 1967 to replace Karachi as the nation's capital. Located in the northern part of the country near the Margalla Hills, the city was purposefully designed and built as a modern planned capital. The city is known for its well-organized layout, wide tree-lined avenues, and systematic sectoral divisions that create an orderly urban environment. Islamabad houses important government buildings, including the Presidential Palace, Parliament House, and Supreme Court of Pakistan. The city is characterized by its clean, green environment with numerous parks, gardens, and the scenic Margalla Hills National Park nearby. Home to several prestigious educational institutions like Quaid-i-Azam University and the International Islamic University, it serves as an important academic center. The population is diverse, consisting of government officials, diplomats, professionals, and students from across Pakistan and abroad. Islamabad's economy is primarily based on government services, though it also has growing technology and business sectors. The city experiences a humid subtropical climate with hot summers and mild winters. As Pakistan's political and administrative center, Islamabad plays a crucial role in the country's governance and international diplomatic relations."}],
       'referenceTaskIds': None,
       'role': 'agent',
       'taskId': None}],
     'id': 'fac87679-acbf-4405-bfb3-36f7bd9e3f3a',
     'kind': 'task',
     'metadata': None,
     'status': {'message': None, 'state': 'completed', 'timestamp': None}}},
   'usage': {'input': 0,
    'output': 0,
    'total': 0,
    'unit': <ModelUsageUnit.TOKENS: 'TOKENS'>},
   'level': <ObservationLevel.DEFAULT: 'DEFAULT'>,
   'statusMessage': None,
   'parentObservationId': 'bfd858f112cad05f',
   'promptId': None,
   'usageDetails': {},
   'costDetails': {},
   'environment': 'default',
   'promptName': None,
   'promptVersion': None,
   'modelId': None,
   'inputPrice': 0.0,
   'outputPrice': 0.0,
   'totalPrice': 0.0,
   'calculatedInputCost': None,
   'calculatedOutputCost': None,
   'calculatedTotalCost': 0.0,
   'latency': 5986.0,
   'timeToFirstToken': None,
   'promptTokens': 0,
   'unit': 'TOKENS',
   'createdAt': '2025-11-20T09:28:31.988Z',
   'updatedAt': '2025-11-20T09:28:31.988Z',
   'totalTokens': 0,
   'projectId': 'cmhwzwyvs01fjad07xfmlp94h',
   'completionTokens': 0},
  {'id': 'a9e7e75088e2edca',
   'traceId': '3c7300a2c603e23e4cd87f07cdc5c34f',
   'type': 'GENERATION',
   'name': 'call_llm',
   'startTime': datetime.datetime(2025, 11, 20, 9, 28, 20, 473000, tzinfo=datetime.timezone.utc),
   'endTime': datetime.datetime(2025, 11, 20, 9, 28, 29, 204000, tzinfo=datetime.timezone.utc),
   'completionStartTime': None,
   'model': 'azure/gpt-4o-mini',
   'modelParameters': {},
   'input': {'model': 'azure/gpt-4o-mini',
    'config': {'system_instruction': '\n        **Role:** Host agent for the agent-to-agent protocol; delegates queries to specialized remote agents with maximum efficiency.\n\n**Core Directives:**\n\n* **Task Delegation:** Use the `send_message` function to assign precise, actionable tasks to remote agents.\n* **Full Context Provision:** If an agent repeatedly asks for user confirmation, it likely lacks conversation history. Include all relevant context in the task to prevent this.\n* **Autonomous Multi-Agent Engagement:** Engage any required agents directly—never seek user permission or preference. If multiple agents are needed, orchestrate them seamlessly.\n* **Intelligent Inter-Agent Collaboration:** Instruct agents to determine if they need data from another agent. **If Agent A says "I need X to proceed" and Agent B can provide X, immediately query Agent B, then resubmit the updated task to Agent A.**\n* **Transparent Output:** Deliver the full, unedited response from the final agent(s) to the user.\n* **Confirmation Handling:** Only relay confirmation requests to the user if not already provided. Never confirm on behalf of the user.\n* **Minimal Context Sharing:** Share only task-relevant context with each agent. Omit irrelevant details.\n* **No Redundancy:** Never ask agents to confirm actions or information.\n* **Tool-Only Responses:** Rely exclusively on tools and agents. If data is missing, request clarification from the user—never assume.\n* **Recency Priority:** Base decisions on the most recent user message.\n* **Active Agent Routing:** Route follow-up queries to the currently active agent using task updates.\n\n**Efficiency Rule:** \n> **Dependency Resolution Loop:**  \n> If Agent A blocks on missing info → Identify Agent B that can supply it → Query B → Feed result back to A → Repeat until A completes or escalates.\n        **Agent Roster:**\n\n        * Available Agents: `{"name": "Capital Agent", "description": "Answers capital-city questions for any country"}\n{"name": "General Q&A Agent", "description": "Answers everyday questions on any topic \\u2014 weather, facts, how-to, recommendations, and more."}`\n        * Currently Active Seller Agent: `Capital Agent`\n                \n\nYou are an agent. Your internal name is "Routing_agent". The description about you is "This Routing agent orchestrates the decomposition of the user asking for department or manager information.".',
     'tools': [{'function_declarations': [{'description': 'Sends a task to remote seller agent.\n\nThis will send a message to the remote agent named agent_name.\n\nArgs:\n    agent_name: The name of the agent to send the task to.\n    task: The comprehensive conversation context summary\n        and goal to be achieved regarding user inquiry and purchase request.\n    tool_context: The tool context this method runs in.\n\nYields:\n    A dictionary of JSON data.\n',
         'name': 'send_message',
         'parameters': {'properties': {'agent_name': {'type': 'STRING'},
           'task': {'type': 'STRING'}},
          'required': ['agent_name', 'task'],
          'type': 'OBJECT'},
         'response': {}}]}],
     'labels': {'adk_agent_name': 'Routing_agent'}},
    'contents': [{'parts': [{'text': 'what is the capital of Pakistan and write 10 lines about it.'}],
      'role': 'user'},
     {'parts': [{'function_call': {'id': 'call_2kkSR1RTSkhmWq7mei1gcBgB',
         'args': {'agent_name': 'Capital Agent',
          'task': 'User requested the capital of Pakistan and a 10-line description about it.'},
         'name': 'send_message'}}],
      'role': 'model'},
     {'parts': [{'function_response': {'id': 'call_2kkSR1RTSkhmWq7mei1gcBgB',
         'name': 'send_message',
         'response': {'result': {'artifacts': [{'artifactId': '3d9b7caa-07e0-45c0-a38a-cc8e3948cdac',
             'parts': [{'kind': 'text', 'text': 'Islamabad'}]}],
           'contextId': 'b6b6d2ce-ca8a-43e5-adbe-999eba9ebd1c',
           'history': [{'contextId': 'b6b6d2ce-ca8a-43e5-adbe-999eba9ebd1c',
             'kind': 'message',
             'messageId': '2aff8a91-f6c0-4fe4-8b98-45aff71b2cf3',
             'parts': [{'kind': 'text', 'text': 'Islamabad'}],
             'role': 'agent'}],
           'id': '998fde21-2f6a-4116-8669-b48ad0d278d9',
           'kind': 'task',
           'status': {'state': 'completed'}}}}}],
      'role': 'user'}]},
   'version': None,
   'metadata': {'attributes': {'gen_ai.system': 'gcp.vertex.agent',
     'gen_ai.request.model': 'azure/gpt-4o-mini',
     'gcp.vertex.agent.invocation_id': 'e-1773c2c0-9fb0-4741-bf2f-4936346cf4da',
     'gcp.vertex.agent.session_id': 'default_session',
     'gcp.vertex.agent.event_id': '5de324d5-9cd4-470e-b86c-83dbc92187b3',
     'gen_ai.usage.input_tokens': '921',
     'gen_ai.usage.output_tokens': '38'},
    'resourceAttributes': {'telemetry.sdk.language': 'python',
     'telemetry.sdk.name': 'opentelemetry',
     'telemetry.sdk.version': '1.38.0',
     'service.name': 'unknown_service'},
    'scope': {'name': 'gcp.vertex.agent',
     'version': '1.17.0',
     'attributes': {}}},
   'output': {'content': {'parts': [{'function_call': {'id': 'call_pQA9a3Ea1lmhaEp6r4EdsWto',
        'args': {'agent_name': 'General Q&A Agent',
         'task': 'User asked for a 10-line description of Islamabad, the capital of Pakistan.'},
        'name': 'send_message'}}],
     'role': 'model'},
    'partial': False,
    'usage_metadata': {'candidates_token_count': 38,
     'prompt_token_count': 921,
     'total_token_count': 959}},
   'usage': {'input': 921,
    'output': 38,
    'total': 959,
    'unit': <ModelUsageUnit.TOKENS: 'TOKENS'>},
   'level': <ObservationLevel.DEFAULT: 'DEFAULT'>,
   'statusMessage': None,
   'parentObservationId': None,
   'promptId': None,
   'usageDetails': {'input': 921, 'output': 38, 'total': 959},
   'costDetails': {},
   'environment': 'default',
   'promptName': None,
   'promptVersion': None,
   'modelId': None,
   'inputPrice': 0.0,
   'outputPrice': 0.0,
   'totalPrice': 0.0,
   'calculatedInputCost': None,
   'calculatedOutputCost': None,
   'calculatedTotalCost': 0.0,
   'latency': 8731.0,
   'timeToFirstToken': None,
   'promptTokens': 921,
   'unit': 'TOKENS',
   'createdAt': '2025-11-20T09:28:31.988Z',
   'updatedAt': '2025-11-20T09:28:31.988Z',
   'totalTokens': 959,
   'projectId': 'cmhwzwyvs01fjad07xfmlp94h',
   'completionTokens': 38},
  {'id': '36d37b6e55229026',
   'traceId': '3c7300a2c603e23e4cd87f07cdc5c34f',
   'type': 'SPAN',
   'name': 'a2a.client.transports.jsonrpc.JsonRpcTransport.send_message',
   'startTime': datetime.datetime(2025, 11, 20, 9, 28, 23, 210000, tzinfo=datetime.timezone.utc),
   'endTime': datetime.datetime(2025, 11, 20, 9, 28, 29, 196000, tzinfo=datetime.timezone.utc),
   'completionStartTime': None,
   'model': None,
   'modelParameters': None,
   'input': None,
   'version': None,
   'metadata': {'attributes': {},
    'resourceAttributes': {'telemetry.sdk.language': 'python',
     'telemetry.sdk.name': 'opentelemetry',
     'telemetry.sdk.version': '1.38.0',
     'service.name': 'unknown_service'},
    'scope': {'name': 'a2a-python-sdk', 'version': '1.0.0', 'attributes': {}}},
   'output': None,
   'usage': {'input': 0,
    'output': 0,
    'total': 0,
    'unit': <ModelUsageUnit.TOKENS: 'TOKENS'>},
   'level': <ObservationLevel.DEFAULT: 'DEFAULT'>,
   'statusMessage': None,
   'parentObservationId': '6eda86706e8e2b96',
   'promptId': None,
   'usageDetails': {},
   'costDetails': {},
   'environment': 'default',
   'promptName': None,
   'promptVersion': None,
   'modelId': None,
   'inputPrice': 0.0,
   'outputPrice': 0.0,
   'totalPrice': 0.0,
   'calculatedInputCost': None,
   'calculatedOutputCost': None,
   'calculatedTotalCost': 0.0,
   'latency': 5986.0,
   'timeToFirstToken': None,
   'promptTokens': 0,
   'unit': 'TOKENS',
   'createdAt': '2025-11-20T09:28:31.988Z',
   'updatedAt': '2025-11-20T09:28:31.988Z',
   'totalTokens': 0,
   'projectId': 'cmhwzwyvs01fjad07xfmlp94h',
   'completionTokens': 0},
  {'id': '8b881a2370954903',
   'traceId': '3c7300a2c603e23e4cd87f07cdc5c34f',
   'type': 'SPAN',
   'name': 'a2a.client.transports.jsonrpc.JsonRpcTransport._send_request',
   'startTime': datetime.datetime(2025, 11, 20, 9, 28, 23, 211000, tzinfo=datetime.timezone.utc),
   'endTime': datetime.datetime(2025, 11, 20, 9, 28, 29, 196000, tzinfo=datetime.timezone.utc),
   'completionStartTime': None,
   'model': None,
   'modelParameters': None,
   'input': None,
   'version': None,
   'metadata': {'attributes': {},
    'resourceAttributes': {'telemetry.sdk.language': 'python',
     'telemetry.sdk.name': 'opentelemetry',
     'telemetry.sdk.version': '1.38.0',
     'service.name': 'unknown_service'},
    'scope': {'name': 'a2a-python-sdk', 'version': '1.0.0', 'attributes': {}}},
   'output': None,
   'usage': {'input': 0,
    'output': 0,
    'total': 0,
    'unit': <ModelUsageUnit.TOKENS: 'TOKENS'>},
   'level': <ObservationLevel.DEFAULT: 'DEFAULT'>,
   'statusMessage': None,
   'parentObservationId': '36d37b6e55229026',
   'promptId': None,
   'usageDetails': {},
   'costDetails': {},
   'environment': 'default',
   'promptName': None,
   'promptVersion': None,
   'modelId': None,
   'inputPrice': 0.0,
   'outputPrice': 0.0,
   'totalPrice': 0.0,
   'calculatedInputCost': None,
   'calculatedOutputCost': None,
   'calculatedTotalCost': 0.0,
   'latency': 5985.0,
   'timeToFirstToken': None,
   'promptTokens': 0,
   'unit': 'TOKENS',
   'createdAt': '2025-11-20T09:28:31.988Z',
   'updatedAt': '2025-11-20T09:28:31.988Z',
   'totalTokens': 0,
   'projectId': 'cmhwzwyvs01fjad07xfmlp94h',
   'completionTokens': 0},
  {'id': 'bfd858f112cad05f',
   'traceId': '3c7300a2c603e23e4cd87f07cdc5c34f',
   'type': 'TOOL',
   'name': 'execute_tool send_message',
   'startTime': datetime.datetime(2025, 11, 20, 9, 28, 23, 209000, tzinfo=datetime.timezone.utc),
   'endTime': datetime.datetime(2025, 11, 20, 9, 28, 29, 199000, tzinfo=datetime.timezone.utc),
   'completionStartTime': None,
   'model': None,
   'modelParameters': {},
   'input': {'agent_name': 'General Q&A Agent',
    'task': 'User asked for a 10-line description of Islamabad, the capital of Pakistan.'},
   'version': None,
   'metadata': {'attributes': {'gen_ai.operation.name': 'execute_tool',
     'gen_ai.tool.description': 'Sends a task to remote seller agent.\n\nThis will send a message to the remote agent named agent_name.\n\nArgs:\n    agent_name: The name of the agent to send the task to.\n    task: The comprehensive conversation context summary\n        and goal to be achieved regarding user inquiry and purchase request.\n    tool_context: The tool context this method runs in.\n\nYields:\n    A dictionary of JSON data.',
     'gen_ai.tool.name': 'send_message',
     'gen_ai.tool.type': 'FunctionTool',
     'gen_ai.tool.call.id': 'call_pQA9a3Ea1lmhaEp6r4EdsWto',
     'gcp.vertex.agent.event_id': '0e7c0a2c-01dc-48f4-9730-70b176b8cb9e'},
    'resourceAttributes': {'telemetry.sdk.language': 'python',
     'telemetry.sdk.name': 'opentelemetry',
     'telemetry.sdk.version': '1.38.0',
     'service.name': 'unknown_service'},
    'scope': {'name': 'gcp.vertex.agent',
     'version': '1.17.0',
     'attributes': {}}},
   'output': {'result': '<not serializable>'},
   'usage': {'input': 0,
    'output': 0,
    'total': 0,
    'unit': <ModelUsageUnit.TOKENS: 'TOKENS'>},
   'level': <ObservationLevel.DEFAULT: 'DEFAULT'>,
   'statusMessage': None,
   'parentObservationId': 'a9e7e75088e2edca',
   'promptId': None,
   'usageDetails': {},
   'costDetails': {},
   'environment': 'default',
   'promptName': None,
   'promptVersion': None,
   'modelId': None,
   'inputPrice': 0.0,
   'outputPrice': 0.0,
   'totalPrice': 0.0,
   'calculatedInputCost': None,
   'calculatedOutputCost': None,
   'calculatedTotalCost': 0.0,
   'latency': 5990.0,
   'timeToFirstToken': None,
   'promptTokens': 0,
   'unit': 'TOKENS',
   'createdAt': '2025-11-20T09:28:31.988Z',
   'updatedAt': '2025-11-20T09:28:31.988Z',
   'totalTokens': 0,
   'projectId': 'cmhwzwyvs01fjad07xfmlp94h',
   'completionTokens': 0},
  {'id': 'd28642acb4e842bb',
   'traceId': '3c7300a2c603e23e4cd87f07cdc5c34f',
   'type': 'SPAN',
   'name': 'a2a.client.transports.jsonrpc.JsonRpcTransport._apply_interceptors',
   'startTime': datetime.datetime(2025, 11, 20, 9, 28, 23, 211000, tzinfo=datetime.timezone.utc),
   'endTime': datetime.datetime(2025, 11, 20, 9, 28, 23, 211000, tzinfo=datetime.timezone.utc),
   'completionStartTime': None,
   'model': None,
   'modelParameters': None,
   'input': None,
   'version': None,
   'metadata': {'attributes': {},
    'resourceAttributes': {'telemetry.sdk.language': 'python',
     'telemetry.sdk.name': 'opentelemetry',
     'telemetry.sdk.version': '1.38.0',
     'service.name': 'unknown_service'},
    'scope': {'name': 'a2a-python-sdk', 'version': '1.0.0', 'attributes': {}}},
   'output': None,
   'usage': {'input': 0,
    'output': 0,
    'total': 0,
    'unit': <ModelUsageUnit.TOKENS: 'TOKENS'>},
   'level': <ObservationLevel.DEFAULT: 'DEFAULT'>,
   'statusMessage': None,
   'parentObservationId': '36d37b6e55229026',
   'promptId': None,
   'usageDetails': {},
   'costDetails': {},
   'environment': 'default',
   'promptName': None,
   'promptVersion': None,
   'modelId': None,
   'inputPrice': 0.0,
   'outputPrice': 0.0,
   'totalPrice': 0.0,
   'calculatedInputCost': None,
   'calculatedOutputCost': None,
   'calculatedTotalCost': 0.0,
   'latency': 0.0,
   'timeToFirstToken': None,
   'promptTokens': 0,
   'unit': 'TOKENS',
   'createdAt': '2025-11-20T09:28:26.608Z',
   'updatedAt': '2025-11-20T09:28:26.609Z',
   'totalTokens': 0,
   'projectId': 'cmhwzwyvs01fjad07xfmlp94h',
   'completionTokens': 0},
  {'id': '2505fd8e73f7c16d',
   'traceId': '3c7300a2c603e23e4cd87f07cdc5c34f',
   'type': 'SPAN',
   'name': 'a2a.client.transports.jsonrpc.JsonRpcTransport._get_http_args',
   'startTime': datetime.datetime(2025, 11, 20, 9, 28, 23, 210000, tzinfo=datetime.timezone.utc),
   'endTime': datetime.datetime(2025, 11, 20, 9, 28, 23, 210000, tzinfo=datetime.timezone.utc),
   'completionStartTime': None,
   'model': None,
   'modelParameters': None,
   'input': None,
   'version': None,
   'metadata': {'attributes': {},
    'resourceAttributes': {'telemetry.sdk.language': 'python',
     'telemetry.sdk.name': 'opentelemetry',
     'telemetry.sdk.version': '1.38.0',
     'service.name': 'unknown_service'},
    'scope': {'name': 'a2a-python-sdk', 'attributes': {}}},
   'output': None,
   'usage': {'input': 0,
    'output': 0,
    'total': 0,
    'unit': <ModelUsageUnit.TOKENS: 'TOKENS'>},
   'level': <ObservationLevel.DEFAULT: 'DEFAULT'>,
   'statusMessage': None,
   'parentObservationId': '36d37b6e55229026',
   'promptId': None,
   'usageDetails': {},
   'costDetails': {},
   'environment': 'default',
   'promptName': None,
   'promptVersion': None,
   'modelId': None,
   'inputPrice': 0.0,
   'outputPrice': 0.0,
   'totalPrice': 0.0,
   'calculatedInputCost': None,
   'calculatedOutputCost': None,
   'calculatedTotalCost': 0.0,
   'latency': 0.0,
   'timeToFirstToken': None,
   'promptTokens': 0,
   'unit': 'TOKENS',
   'createdAt': '2025-11-20T09:28:26.608Z',
   'updatedAt': '2025-11-20T09:28:26.608Z',
   'totalTokens': 0,
   'projectId': 'cmhwzwyvs01fjad07xfmlp94h',
   'completionTokens': 0}],
 'scores': [],
 'bookmarked': False,
 'createdAt': '2025-11-20T09:28:27.000Z',
 'updatedAt': '2025-11-20T09:28:32.069Z',
 'projectId': 'cmhwzwyvs01fjad07xfmlp94h',
 'sessionId': None,
 'release': None,
 'version': None,
 'userId': None,
 'externalId': None}